version: "3.8"

services:
  go_srv_service3:
    image: go_server_in_container:method3
    container_name: go_srv_container3
    hostname: go_srv_host3
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8080"         # ← this needs to be a list format
    depends_on:
      - pg_service3         # ← also should be a list
    networks:
      - custom_net3

  pg_service3:
    container_name: pg_container3
    hostname: pg_host3
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: requestsdb_docker
      POSTGRES_HOST_AUTH_METHOD: trust   # ← Add this line if no password is set
    volumes:
      - pg_data3:/var/lib/postgresql/data
    networks:
      - custom_net3

networks:
  custom_net3:

volumes:
  pg_data3:
